In [1]:
import pandas as pd
df = pd.read_csv('output.csv')

In [2]:
df

,Unnamed: 0,Marital_status,Application_mode,Application_order,Course,Daytime_evening_attendance,Previous_qualification,Nacionality,Mothers_qualification,Fathers_qualification,...,Curricular_units_2nd_sem_credited,Curricular_units_2nd_sem_enrolled,Curricular_units_2nd_sem_evaluations,Curricular_units_2nd_sem_approved,Curricular_units_2nd_sem_grade,Curricular_units_2nd_sem_without_evaluations,Unemployment_rate,Inflation_rate,GDP,Target
0,0,1.0,8.000000,5.00000,2.000000,1.0,1.0,1.000000,13.0,10.0,...,0.0,0.271336,0.000000,0.00,0.000000,0.000000,0.459776,0.488889,0.766182,Dropout
1,2,1.0,1.000000,5.00000,5.000000,1.0,1.0,1.000000,22.0,27.0,...,0.0,0.260870,0.000000,0.00,0.000000,0.000000,0.372093,0.488889,0.766182,Dropout
2,3,1.0,8.000000,2.00000,15.000000,1.0,1.0,1.000000,23.0,27.0,...,0.0,0.260870,0.303030,0.25,0.667692,0.000000,0.209302,0.000000,0.536240,Graduate
3,4,2.0,12.000000,1.72214,3.000000,0.0,1.0,1.000000,22.0,28.0,...,0.0,0.260870,0.181818,0.30,0.550720,0.000000,0.732558,0.111111,0.640687,Graduate
4,5,2.0,12.000000,1.00000,17.000000,0.0,12.0,1.000000,22.0,27.0,...,0.0,0.217391,0.515152,0.25,0.619231,0.012079,1.000000,0.244444,0.414795,Graduate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3962,4419,1.0,1.000000,6.00000,15.000000,1.0,1.0,1.232363,1.0,1.0,...,0.0,0.260870,0.242424,0.25,0.682051,0.000000,0.918605,0.800000,0.000000,Graduate
3963,4420,1.0,6.925098,2.00000,15.000000,1.0,1.0,19.000000,1.0,1.0,...,0.0,0.260870,0.244653,0.10,0.550720,0.000000,0.406977,0.311111,0.803170,Dropout
3964,4421,1.0,1.000000,1.00000,12.000000,1.0,1.0,1.000000,22.0,27.0,...,0.0,0.347826,0.244653,0.05,0.726923,0.000000,0.732558,0.449027,0.640687,Dropout
3965,4422,1.0,1.000000,1.00000,9.910415,1.0,1.0,1.000000,22.0,27.0,...,0.0,0.217391,0.181818,0.25,0.646154,0.000000,0.209302,0.000000,0.124174,Graduate
3966,4423,1.0,5.000000,1.00000,15.000000,1.0,1.0,9.000000,23.0,27.0,...,0.0,0.260870,0.181818,0.30,0.700000,0.000000,0.593023,0.449027,0.311757,Graduate

In [3]:
df = df.drop(columns=["Unnamed: 0"])

In [4]:
df

,Marital_status,Application_mode,Application_order,Course,Daytime_evening_attendance,Previous_qualification,Nacionality,Mothers_qualification,Fathers_qualification,Mothers_occupation,...,Curricular_units_2nd_sem_credited,Curricular_units_2nd_sem_enrolled,Curricular_units_2nd_sem_evaluations,Curricular_units_2nd_sem_approved,Curricular_units_2nd_sem_grade,Curricular_units_2nd_sem_without_evaluations,Unemployment_rate,Inflation_rate,GDP,Target
0,1.0,8.000000,5.00000,2.000000,1.0,1.0,1.000000,13.0,10.0,6.000000,...,0.0,0.271336,0.000000,0.00,0.000000,0.000000,0.459776,0.488889,0.766182,Dropout
1,1.0,1.000000,5.00000,5.000000,1.0,1.0,1.000000,22.0,27.0,10.000000,...,0.0,0.260870,0.000000,0.00,0.000000,0.000000,0.372093,0.488889,0.766182,Dropout
2,1.0,8.000000,2.00000,15.000000,1.0,1.0,1.000000,23.0,27.0,6.000000,...,0.0,0.260870,0.303030,0.25,0.667692,0.000000,0.209302,0.000000,0.536240,Graduate
3,2.0,12.000000,1.72214,3.000000,0.0,1.0,1.000000,22.0,28.0,10.000000,...,0.0,0.260870,0.181818,0.30,0.550720,0.000000,0.732558,0.111111,0.640687,Graduate
4,2.0,12.000000,1.00000,17.000000,0.0,12.0,1.000000,22.0,27.0,7.332924,...,0.0,0.217391,0.515152,0.25,0.619231,0.012079,1.000000,0.244444,0.414795,Graduate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3962,1.0,1.000000,6.00000,15.000000,1.0,1.0,1.232363,1.0,1.0,6.000000,...,0.0,0.260870,0.242424,0.25,0.682051,0.000000,0.918605,0.800000,0.000000,Graduate
3963,1.0,6.925098,2.00000,15.000000,1.0,1.0,19.000000,1.0,1.0,10.000000,...,0.0,0.260870,0.244653,0.10,0.550720,0.000000,0.406977,0.311111,0.803170,Dropout
3964,1.0,1.000000,1.00000,12.000000,1.0,1.0,1.000000,22.0,27.0,10.000000,...,0.0,0.347826,0.244653,0.05,0.726923,0.000000,0.732558,0.449027,0.640687,Dropout
3965,1.0,1.000000,1.00000,9.910415,1.0,1.0,1.000000,22.0,27.0,8.000000,...,0.0,0.217391,0.181818,0.25,0.646154,0.000000,0.209302,0.000000,0.124174,Graduate
3966,1.0,5.000000,1.00000,15.000000,1.0,1.0,9.000000,23.0,27.0,7.332924,...,0.0,0.260870,0.181818,0.30,0.700000,0.000000,0.593023,0.449027,0.311757,Graduate

In [5]:
categorical_cols = [
    'Marital_status','Application_mode','Application_order','Course',
    'Daytime_evening_attendance','Previous_qualification','Nacionality',
    'Mothers_qualification','Fathers_qualification','Mothers_occupation',
    'Fathers_occupation','Displaced','Educational_special_needs','Debtor',
    'Tuition_fees_up_to_date','Gender','Scholarship_holder','International'
]

df[categorical_cols] = df[categorical_cols].astype(int)

In [7]:
df

,Marital_status,Application_mode,Application_order,Course,Daytime_evening_attendance,Previous_qualification,Nacionality,Mothers_qualification,Fathers_qualification,Mothers_occupation,...,Curricular_units_2nd_sem_credited,Curricular_units_2nd_sem_enrolled,Curricular_units_2nd_sem_evaluations,Curricular_units_2nd_sem_approved,Curricular_units_2nd_sem_grade,Curricular_units_2nd_sem_without_evaluations,Unemployment_rate,Inflation_rate,GDP,Target
0,1,8,5,2,1,1,1,13,10,6,...,0.0,0.271336,0.000000,0.00,0.000000,0.000000,0.459776,0.488889,0.766182,Dropout
1,1,1,5,5,1,1,1,22,27,10,...,0.0,0.260870,0.000000,0.00,0.000000,0.000000,0.372093,0.488889,0.766182,Dropout
2,1,8,2,15,1,1,1,23,27,6,...,0.0,0.260870,0.303030,0.25,0.667692,0.000000,0.209302,0.000000,0.536240,Graduate
3,2,12,1,3,0,1,1,22,28,10,...,0.0,0.260870,0.181818,0.30,0.550720,0.000000,0.732558,0.111111,0.640687,Graduate
4,2,12,1,17,0,12,1,22,27,7,...,0.0,0.217391,0.515152,0.25,0.619231,0.012079,1.000000,0.244444,0.414795,Graduate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3962,1,1,6,15,1,1,1,1,1,6,...,0.0,0.260870,0.242424,0.25,0.682051,0.000000,0.918605,0.800000,0.000000,Graduate
3963,1,6,2,15,1,1,19,1,1,10,...,0.0,0.260870,0.244653,0.10,0.550720,0.000000,0.406977,0.311111,0.803170,Dropout
3964,1,1,1,12,1,1,1,22,27,10,...,0.0,0.347826,0.244653,0.05,0.726923,0.000000,0.732558,0.449027,0.640687,Dropout
3965,1,1,1,9,1,1,1,22,27,8,...,0.0,0.217391,0.181818,0.25,0.646154,0.000000,0.209302,0.000000,0.124174,Graduate
3966,1,5,1,15,1,1,9,23,27,7,...,0.0,0.260870,0.181818,0.30,0.700000,0.000000,0.593023,0.449027,0.311757,Graduate

In [6]:
df.to_csv("weka_ready.csv", index=False)